name: last nest build  # 현재 제목

on:  # 이벤트를 등록
  push:  # push 이벤트가 발생하면
    branches:  # branches 어떤 브랜치에 이벤트가 일어났을 때 작업을 동작시킨다.
      - main

jobs:  # 작업의 단위
  Build:  # 식별자 (이름 내 맘대로)
    runs-on: ubuntu-latest  # 러너에서 사용할 os latest 최신 버전 사용하겠다.

    steps:  # 작업의 가장 작은 단위
      - name: checkout  # 작업의 작은 단위의 이름
        uses: actions/checkout@v4  # 레파지토리를 체크아웃 할 수 있게 도와주는 라이브러리
        # 브런치에 있는 내용을 클론해온다. workflow에 복사해온다.

      - name: set up node  # uses 라이브러리를 사용할 것을 가져오고, with : 라이브러리의 속성 설정
        uses: actions/setup-node@v4  # 노드 버전 가져오기
        with:
          node-version: '20'  # 20 버전의 노트 런타임 환경을 제공

      - name: npm test  # 의존성을 설치하기 전에 폴더 구조 확인. pwd 현재 작업환경의 경로
        run: |
          ls
          pwd