name : CI/CD 구축
on:
  push:
    branches:
      - main
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4 # uses 사용할 라이브러리

        - name: ssh ec2 접속
          uses: appleboy/ssh-action@v1.0.3
          with: 
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.AWS_SECRET_KEY }}
            port: ${{ secrets.PORT }}
            script: | # 실행할 스크립트
                cd /home/ubuntu/myapp
                git pull origin main
                pm2 kill
                npm start
